package module

import (
	"os"
	"path/filepath"

	"github.com/BurntSushi/toml"
)

// LockFile represents the carv.lock file that pins exact dependency versions.
type LockFile struct {
	Packages []LockedPackage `toml:"package"`
}

// LockedPackage represents a single locked dependency.
type LockedPackage struct {
	Name     string `toml:"name"`
	Version  string `toml:"version"`
	Source   string `toml:"source"`
	Revision string `toml:"revision"`
}

// LoadLock reads carv.lock from the given project directory.
func LoadLock(dir string) (*LockFile, error) {
	lockPath := filepath.Join(dir, "carv.lock")

	data, err := os.ReadFile(lockPath)
	if err != nil {
		if os.IsNotExist(err) {
			return &LockFile{}, nil
		}
		return nil, err
	}

	var lf LockFile
	if err := toml.Unmarshal(data, &lf); err != nil {
		return nil, err
	}

	return &lf, nil
}

// SaveLock writes carv.lock to the given project directory.
func SaveLock(dir string, lf *LockFile) error {
	lockPath := filepath.Join(dir, "carv.lock")

	f, err := os.Create(lockPath)
	if err != nil {
		return err
	}
	defer f.Close()

	if _, err := f.WriteString("# Auto-generated by carv install. Do not edit.\n\n"); err != nil {
		return err
	}

	encoder := toml.NewEncoder(f)
	return encoder.Encode(lf)
}
